/*
 * efiboot.c - minimal self-contained EFI bootloader for the MikroTik boot kit
 *
 * Installed as \EFI\BOOT\BOOTKIT.EFI on the RouterOS EFI system partition,
 * this replaces the EFI shell + startup.nsh trick the kit used before: the
 * loader reads the stock kernel from \EFI\BOOT\BOOTX64.EFI (left in place so
 * RouterOS updates overwrite it with the new kernel) and carries the initramfs
 * (initrd_so.h, generated by build.sh) embedded in itself, then enters the
 * kernel through the x86 EFI handover protocol.
 *
 *   \EFI\BOOT\BOOTKIT.EFI   this loader, with the initramfs embedded; the
 *                           firmware reaches it through a Boot#### entry
 *   \EFI\BOOT\BOOTX64.EFI   stock RouterOS kernel (EFI-stub bzImage)
 *
 * The handover protocol (Documentation/x86/boot.rst) is used instead of the
 * raw 32/64-bit boot protocol on purpose: the entry point is the kernel's own
 * EFI stub, which preserves the EFI runtime environment (efi_info, memory map,
 * setup_graphics, ...) that the RouterOS init relies on.  The loader only has
 * to set up a struct boot_params and call the handover entry; the stub
 * relocates the kernel to its preferred address, exits boot services and
 * jumps into the decompressor.
 *
 * Build: ./build.sh -> bootkit.efi
 *   clang --target=x86_64-unknown-windows (PE32+, subsystem 10), freestanding,
 *   no libc, no gnu-efi.
 */

/* ---- configuration (compile-time) -------------------------------------- */

#define KERNEL_PATH	L"\\EFI\\BOOT\\BOOTX64.EFI"
#define KERNEL_CMDLINE	"console=ttyS0,115200n8 rdinit=/ptrace_init"

/* the initramfs (cpio with /ptrace_init), embedded by build.sh */
#include "initrd_so.h"

/* ---- EFI essentials (self-contained subset) ---------------------------- */

typedef unsigned char		UINT8;
typedef unsigned short		UINT16;
typedef unsigned int		UINT32;
typedef unsigned long long	UINT64;
typedef signed short		INT16;
typedef signed long long	INT64;
typedef unsigned long long	UINTN;	/* LLP64: long is 32-bit on Windows targets */
typedef UINT16			CHAR16;
typedef UINT8			BOOLEAN;
typedef void			VOID;

#define EFIAPI __attribute__((ms_abi))
#define EFI_PAGE_SIZE 4096
#define EFI_SIZE_TO_PAGES(n) (((n) + EFI_PAGE_SIZE - 1) / EFI_PAGE_SIZE)

typedef UINTN EFI_STATUS;
typedef VOID *EFI_HANDLE;
typedef VOID *EFI_EVENT;
typedef UINT64 EFI_PHYSICAL_ADDRESS;
typedef UINT64 EFI_VIRTUAL_ADDRESS;
typedef UINTN EFI_TPL;

#define EFI_ERROR(s) ((INT64)(s) < 0)
#define EFI_SUCCESS		0
#define EFI_LOAD_ERROR		(1ULL | (1ULL << 63))
#define EFI_INVALID_PARAMETER	(2ULL | (1ULL << 63))
#define EFI_UNSUPPORTED		(3ULL | (1ULL << 63))
#define EFI_BUFFER_TOO_SMALL	(5ULL | (1ULL << 63))
#define EFI_DEVICE_ERROR	(7ULL | (1ULL << 63))
#define EFI_OUT_OF_RESOURCES	(9ULL | (1ULL << 63))
#define EFI_NOT_FOUND		(14ULL | (1ULL << 63))

typedef enum {
	AllocateAnyPages = 0,
	AllocateMaxAddress = 1,
	AllocateAddress = 2
} EFI_ALLOCATE_TYPE;

typedef enum {
	EfiReservedMemoryType = 0,
	EfiLoaderCode = 1,
	EfiLoaderData = 2,
	EfiBootServicesCode = 3,
	EfiBootServicesData = 4,
	EfiRuntimeServicesCode = 5,
	EfiRuntimeServicesData = 6,
	EfiConventionalMemory = 7
} EFI_MEMORY_TYPE;

typedef struct {
	UINT32 Data1;
	UINT16 Data2;
	UINT16 Data3;
	UINT8 Data4[8];
} EFI_GUID;

typedef struct {
	UINT64 Signature;
	UINT32 Revision;
	UINT32 HeaderSize;
	UINT32 CRC32;
	UINT32 Reserved;
} EFI_TABLE_HEADER;

typedef struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;
struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL {
	EFI_STATUS (EFIAPI *Reset)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, BOOLEAN);
	EFI_STATUS (EFIAPI *OutputString)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, CHAR16 *);
	EFI_STATUS (EFIAPI *TestString)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, CHAR16 *);
	EFI_STATUS (EFIAPI *QueryMode)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN, UINTN *, UINTN *);
	EFI_STATUS (EFIAPI *SetMode)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN);
	EFI_STATUS (EFIAPI *SetAttribute)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN);
	EFI_STATUS (EFIAPI *ClearScreen)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *);
	EFI_STATUS (EFIAPI *SetCursorPosition)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN, UINTN);
	EFI_STATUS (EFIAPI *EnableCursor)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, BOOLEAN);
	VOID *Mode;
};

typedef struct EFI_BOOT_SERVICES EFI_BOOT_SERVICES;
struct EFI_BOOT_SERVICES {
	EFI_TABLE_HEADER Hdr;
	EFI_TPL (EFIAPI *RaiseTPL)(EFI_TPL);
	VOID (EFIAPI *RestoreTPL)(EFI_TPL);
	EFI_STATUS (EFIAPI *AllocatePages)(EFI_ALLOCATE_TYPE, EFI_MEMORY_TYPE, UINTN,
					   EFI_PHYSICAL_ADDRESS *);
	EFI_STATUS (EFIAPI *FreePages)(EFI_PHYSICAL_ADDRESS, UINTN);
	EFI_STATUS (EFIAPI *GetMemoryMap)(UINTN *, VOID *, UINTN *, UINTN *, UINT32 *);
	EFI_STATUS (EFIAPI *AllocatePool)(EFI_MEMORY_TYPE, UINTN, VOID **);
	EFI_STATUS (EFIAPI *FreePool)(VOID *);
	VOID *CreateEvent;
	VOID *SetTimer;
	VOID *WaitForEvent;
	VOID *SignalEvent;
	VOID *CloseEvent;
	VOID *CheckEvent;
	VOID *InstallProtocolInterface;
	VOID *ReinstallProtocolInterface;
	VOID *UninstallProtocolInterface;
	EFI_STATUS (EFIAPI *HandleProtocol)(EFI_HANDLE, EFI_GUID *, VOID **);
	VOID *Reserved;
	VOID *RegisterProtocolNotify;
	VOID *LocateHandle;
	VOID *LocateDevicePath;
	VOID *InstallConfigurationTable;
	VOID *LoadImage;
	VOID *StartImage;
	VOID *Exit;
	VOID *UnloadImage;
	VOID *ExitBootServices;
	VOID *GetNextMonotonicCount;
	EFI_STATUS (EFIAPI *Stall)(UINTN);
	VOID *SetWatchdogTimer;
	VOID *ConnectController;
	VOID *DisconnectController;
	VOID *OpenProtocol;
	VOID *CloseProtocol;
	VOID *OpenProtocolInformation;
	VOID *ProtocolsPerHandle;
	VOID *LocateHandleBuffer;
	VOID *LocateProtocol;
	VOID *InstallMultipleProtocolInterfaces;
	VOID *UninstallMultipleProtocolInterfaces;
	VOID *CalculateCrc32;
	VOID *CopyMem;
	VOID *SetMem;
	VOID *CreateEventEx;
};

typedef struct {
	EFI_TABLE_HEADER Hdr;
	CHAR16 *FirmwareVendor;
	UINT32 FirmwareRevision;
	EFI_HANDLE ConsoleInHandle;
	VOID *ConIn;
	EFI_HANDLE ConsoleOutHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *ConOut;
	EFI_HANDLE StandardErrorHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *StdErr;
	VOID *RuntimeServices;
	EFI_BOOT_SERVICES *BootServices;
	UINTN NumberOfTableEntries;
	VOID *ConfigurationTable;
} EFI_SYSTEM_TABLE;

typedef struct {
	UINT32 Revision;
	UINT32 _pad;
	EFI_HANDLE ParentHandle;
	EFI_SYSTEM_TABLE *SystemTable;
	EFI_HANDLE DeviceHandle;
	VOID *FilePath;
	VOID *Reserved;
	UINT32 LoadOptionsSize;
	UINT32 _pad2;
	VOID *LoadOptions;
	VOID *ImageBase;
	UINT64 ImageSize;
	UINT32 ImageCodeType;
	UINT32 ImageDataType;
	VOID *Unload;
} EFI_LOADED_IMAGE_PROTOCOL;

typedef struct EFI_FILE_PROTOCOL EFI_FILE_PROTOCOL;
struct EFI_FILE_PROTOCOL {
	UINT64 Revision;
	EFI_STATUS (EFIAPI *Open)(EFI_FILE_PROTOCOL *, EFI_FILE_PROTOCOL **, CHAR16 *,
				  UINT64, UINT64);
	EFI_STATUS (EFIAPI *Close)(EFI_FILE_PROTOCOL *);
	EFI_STATUS (EFIAPI *Delete)(EFI_FILE_PROTOCOL *);
	EFI_STATUS (EFIAPI *Read)(EFI_FILE_PROTOCOL *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *Write)(EFI_FILE_PROTOCOL *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *GetPosition)(EFI_FILE_PROTOCOL *, UINT64 *);
	EFI_STATUS (EFIAPI *SetPosition)(EFI_FILE_PROTOCOL *, UINT64);
	EFI_STATUS (EFIAPI *GetInfo)(EFI_FILE_PROTOCOL *, EFI_GUID *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *SetInfo)(EFI_FILE_PROTOCOL *, EFI_GUID *, UINTN, VOID *);
	EFI_STATUS (EFIAPI *Flush)(EFI_FILE_PROTOCOL *);
	VOID *OpenEx;
	VOID *ReadEx;
	VOID *WriteEx;
	VOID *FlushEx;
};

typedef struct {
	UINT64 Revision;
	EFI_STATUS (EFIAPI *OpenVolume)(VOID *, EFI_FILE_PROTOCOL **);
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

typedef struct {
	UINT16 Year;
	UINT8 Month;
	UINT8 Day;
	UINT8 Hour;
	UINT8 Minute;
	UINT8 Second;
	UINT8 _pad1;
	UINT32 Nanosecond;
	INT16 TimeZone;
	UINT8 Daylight;
	UINT8 _pad2;
} EFI_TIME;

typedef struct {
	UINT64 Size;
	UINT64 FileSize;
	UINT64 PhysicalSize;
	EFI_TIME CreationTime;
	EFI_TIME LastAccessTime;
	EFI_TIME ModificationTime;
	UINT64 Attribute;
	CHAR16 FileName[1];
} EFI_FILE_INFO;

static EFI_GUID loaded_image_protocol_guid = {
	0x5b1b31a1, 0x9562, 0x11d2, { 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID simple_file_system_guid = {
	0x0964e5b22, 0x6459, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID file_info_guid = {
	0x09576e92, 0x6d3f, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};

#define EFI_FILE_MODE_READ 0x0000000000000001ULL

/* ---- x86 boot protocol structures -------------------------------------- */

struct SetupHeader {
	UINT8 setup_sects;
	UINT16 root_flags;
	UINT32 syssize;
	UINT16 ram_size;
	UINT16 vid_mode;
	UINT16 root_dev;
	UINT16 boot_flag;
	UINT8 jump;
	UINT8 setup_size;
	UINT32 header;
	UINT16 version;
	UINT32 realmode_swtch;
	UINT16 start_sys_seg;
	UINT16 kernel_version;
	UINT8 type_of_loader;
	UINT8 loadflags;
	UINT16 setup_move_size;
	UINT32 code32_start;
	UINT32 ramdisk_image;
	UINT32 ramdisk_size;
	UINT32 bootsect_kludge;
	UINT16 heap_end_ptr;
	UINT8 ext_loader_ver;
	UINT8 ext_loader_type;
	UINT32 cmd_line_ptr;
	UINT32 initrd_addr_max;
	UINT32 kernel_alignment;
	UINT8 relocatable_kernel;
	UINT8 min_alignment;
	UINT16 xloadflags;
	UINT32 cmdline_size;
	UINT32 hardware_subarch;
	UINT64 hardware_subarch_data;
	UINT32 payload_offset;
	UINT32 payload_length;
	UINT64 setup_data;
	UINT64 pref_address;
	UINT32 init_size;
	UINT32 handover_offset;
	UINT32 kernel_info_offset;
} __attribute__((packed));

#define SETUP_HDR_OFFSET	0x1f1
#define SETUP_HDR_MAGIC		0x53726448	/* "HdrS" */
#define BOOT_FLAG_MAGIC		0xaa55
#define SETUP_VERSION_2_11	0x20b
#define SETUP_VERSION_2_12	0x20c

#define XLF_KERNEL_64			(1 << 0)
#define XLF_CAN_BE_LOADED_ABOVE_4G	(1 << 1)
#define XLF_EFI_HANDOVER_32		(1 << 2)
#define XLF_EFI_HANDOVER_64		(1 << 3)

struct BootParams {
	UINT8 _pad0[0xc0];
	UINT32 ext_ramdisk_image;
	UINT32 ext_ramdisk_size;
	UINT32 ext_cmd_line_ptr;
	UINT8 _pad1[SETUP_HDR_OFFSET - 0xcc];
	struct SetupHeader hdr;
	UINT8 _pad2[4096 - SETUP_HDR_OFFSET - sizeof(struct SetupHeader)];
} __attribute__((packed));

_Static_assert(__builtin_offsetof(struct BootParams, ext_ramdisk_image) == 0xc0, "boot_params layout");
_Static_assert(__builtin_offsetof(struct BootParams, ext_cmd_line_ptr) == 0xc8, "boot_params layout");
_Static_assert(__builtin_offsetof(struct BootParams, hdr) == SETUP_HDR_OFFSET, "boot_params layout");
_Static_assert(sizeof(struct BootParams) == 4096, "boot_params layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, header) == 0x11, "setup header layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, code32_start) == 0x23, "setup header layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, handover_offset) == 0x73, "setup header layout");

/* the handover entry point is kernel code: SysV ABI, not the EFI ABI */
typedef void (*handover_fn)(VOID *handle, EFI_SYSTEM_TABLE *st,
			    struct BootParams *params) __attribute__((sysv_abi));

/* ---- runtime helpers --------------------------------------------------- */

static EFI_SYSTEM_TABLE *ST;
static EFI_BOOT_SERVICES *BS;

/* kept out of efi_main's stack frame: >4 KiB frames need a __chkstk probe */
static UINT8 first_page[4096];

/*
 * The image is fully position independent, so without this the linker would
 * emit no base relocations at all and firmware could not load the image
 * anywhere but its preferred base (0x140000000).  One self-referencing
 * pointer forces a .reloc section.
 */
static const VOID *const force_relocation __attribute__((used)) = &force_relocation;

/*
 * clang may turn bulk copies/clears into mem*() calls; keep the definitions
 * local and stop the compiler from re-recognising the loops as builtins.
 */
__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memcpy(VOID *dst, const VOID *src, UINTN n)
{
	UINT8 *d = dst;
	const UINT8 *s = src;

	while (n--)
		*d++ = *s++;
	return dst;
}

__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memmove(VOID *dst, const VOID *src, UINTN n)
{
	UINT8 *d = dst;
	const UINT8 *s = src;

	if (d < s)
		while (n--)
			*d++ = *s++;
	else {
		d += n;
		s += n;
		while (n--)
			*--d = *--s;
	}
	return dst;
}

__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memset(VOID *dst, int c, UINTN n)
{
	UINT8 *d = dst;

	while (n--)
		*d++ = (UINT8)c;
	return dst;
}

static VOID print(CHAR16 *s)
{
	ST->ConOut->OutputString(ST->ConOut, s);
}

static VOID print_hex(UINT64 v)
{
	static const CHAR16 digits[] = L"0123456789abcdef";
	CHAR16 buf[19];
	UINTN i;

	buf[0] = L'0';
	buf[1] = L'x';
	for (i = 0; i < 16; i++)
		buf[2 + i] = digits[(v >> ((15 - i) * 4)) & 0xf];
	buf[18] = 0;
	print(buf);
}

static VOID print_dec(UINT64 v)
{
	CHAR16 buf[21];
	UINTN i = 20;

	buf[i] = 0;
	if (!v)
		buf[--i] = L'0';
	while (v) {
		buf[--i] = (CHAR16)(L'0' + v % 10);
		v /= 10;
	}
	print(buf + i);
}

static EFI_STATUS fail(EFI_STATUS status, CHAR16 *msg)
{
	print(L"efiboot: ");
	print(msg);
	print(L" (status ");
	print_hex(status);
	print(L")\r\n");
	BS->Stall(5000000);
	return status;
}

/* ---- file access ------------------------------------------------------- */

static EFI_STATUS open_root(EFI_HANDLE image, EFI_FILE_PROTOCOL **root)
{
	EFI_LOADED_IMAGE_PROTOCOL *li;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
	EFI_STATUS status;

	status = BS->HandleProtocol(image, &loaded_image_protocol_guid, (VOID **)&li);
	if (EFI_ERROR(status))
		return status;
	status = BS->HandleProtocol(li->DeviceHandle, &simple_file_system_guid, (VOID **)&fs);
	if (EFI_ERROR(status))
		return status;
	return fs->OpenVolume(fs, root);
}

static EFI_STATUS open_file(EFI_FILE_PROTOCOL *root, CHAR16 *path, EFI_FILE_PROTOCOL **f)
{
	return root->Open(root, f, path, EFI_FILE_MODE_READ, 0);
}

static EFI_STATUS file_size(EFI_FILE_PROTOCOL *f, UINT64 *size)
{
	EFI_FILE_INFO *info;
	EFI_STATUS status;
	UINTN buf_size = 560;
	UINT8 buf[560];

	status = f->GetInfo(f, &file_info_guid, &buf_size, buf);
	if (EFI_ERROR(status))
		return status;
	info = (EFI_FILE_INFO *)buf;
	*size = info->FileSize;
	return EFI_SUCCESS;
}

/* read [off, off+len) into buf; the buffer must be large enough */
static EFI_STATUS read_file(EFI_FILE_PROTOCOL *f, UINT64 off, VOID *buf, UINTN len)
{
	EFI_STATUS status;
	UINT8 *p = buf;

	status = f->SetPosition(f, off);
	if (EFI_ERROR(status))
		return status;
	while (len) {
		UINTN n = len;

		status = f->Read(f, &n, p);
		if (EFI_ERROR(status))
			return status;
		if (n == 0)
			return EFI_LOAD_ERROR;	/* short file */
		p += n;
		len -= n;
	}
	return EFI_SUCCESS;
}

static EFI_STATUS alloc_pages(EFI_MEMORY_TYPE type, UINTN size,
			      EFI_PHYSICAL_ADDRESS max_addr, VOID **out)
{
	EFI_PHYSICAL_ADDRESS addr = max_addr;
	EFI_STATUS status;

	status = BS->AllocatePages(AllocateMaxAddress, type,
				   EFI_SIZE_TO_PAGES(size), &addr);
	if (EFI_ERROR(status))
		return status;
	*out = (VOID *)(UINTN)addr;
	return EFI_SUCCESS;
}

/* ---- boot -------------------------------------------------------------- */

static VOID print_kernel_version(const UINT8 *kbuf, UINTN klen)
{
	const struct SetupHeader *h = (const struct SetupHeader *)(kbuf + SETUP_HDR_OFFSET);
	UINT64 off = (UINT64)h->kernel_version + 0x200;
	CHAR16 buf[128];
	UINTN i = 0;

	if (h->kernel_version == 0 || off >= klen)
		return;
	while (i < sizeof(buf) / sizeof(buf[0]) - 1 && off + i < klen && kbuf[off + i]) {
		buf[i] = (CHAR16)kbuf[off + i];
		i++;
	}
	buf[i] = 0;
	if (i) {
		print(L"efiboot: kernel ");
		print(buf);
		print(L"\r\n");
	}
}

EFI_STATUS EFIAPI efi_main(EFI_HANDLE image, EFI_SYSTEM_TABLE *st)
{
	struct SetupHeader hdr;
	struct BootParams *params;
	EFI_FILE_PROTOCOL *root, *f;
	EFI_PHYSICAL_ADDRESS addr;
	EFI_STATUS status;
	UINTN setup_sects, setup_total, kalloc;
	UINT64 kfile_size, kneed, klen, ilen;
	UINT8 *kbuf = 0, *ibuf = 0;
	CHAR16 *cmd;
	handover_fn handover;

	ST = st;
	BS = st->BootServices;

	print(L"efiboot: MikroTik boot kit loader\r\n");

	status = open_root(image, &root);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open the boot volume");

	/* -- kernel: read the first page, validate, then load it below 4G -- */

	status = open_file(root, KERNEL_PATH, &f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open " KERNEL_PATH);

	status = file_size(f, &klen);
	if (EFI_ERROR(status))
		return fail(status, L"cannot size the kernel");
	if (klen < sizeof(first_page))
		return fail(EFI_LOAD_ERROR, L"kernel file is too small");
	status = read_file(f, 0, first_page, sizeof(first_page));
	if (EFI_ERROR(status))
		return fail(status, L"cannot read the kernel");

	memcpy(&hdr, first_page + SETUP_HDR_OFFSET, sizeof(hdr));
	if (hdr.boot_flag != BOOT_FLAG_MAGIC || hdr.header != SETUP_HDR_MAGIC)
		return fail(EFI_LOAD_ERROR, L"not a Linux bzImage");
	if (hdr.version < SETUP_VERSION_2_11)
		return fail(EFI_UNSUPPORTED, L"kernel is too old for EFI handover");
	if (!hdr.relocatable_kernel)
		return fail(EFI_UNSUPPORTED, L"kernel is not relocatable");
	if (!(hdr.xloadflags & XLF_KERNEL_64) ||
	    !(hdr.xloadflags & XLF_EFI_HANDOVER_64))
		return fail(EFI_UNSUPPORTED, L"kernel has no 64-bit EFI handover entry");
	if (!hdr.syssize || !hdr.init_size)
		return fail(EFI_LOAD_ERROR, L"kernel image sizes are invalid");

	setup_sects = hdr.setup_sects ? hdr.setup_sects : 4;
	setup_total = (setup_sects + 1) * 512;
	kfile_size = setup_total + (UINT64)hdr.syssize * 16;
	if (kfile_size > klen)
		return fail(EFI_LOAD_ERROR, L"kernel image is truncated");

	/*
	 * The EFI stub copies hdr.init_size bytes starting at the protected-mode
	 * entry when it relocates the kernel, so reserve that much even when the
	 * file itself is smaller; the tail stays zero.
	 */
	kneed = setup_total + hdr.init_size;
	kalloc = (UINTN)(kneed > kfile_size ? kneed : kfile_size);
	status = alloc_pages(EfiLoaderCode, kalloc, 0xffffffffULL, (VOID **)&kbuf);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate kernel memory");
	memset(kbuf, 0, kalloc);
	status = read_file(f, 0, kbuf, (UINTN)kfile_size);
	f->Close(f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot load the kernel");

	print_kernel_version(kbuf, kalloc);

	/* -- initrd: copy the embedded cpio below initrd_addr_max (0x7fffffff) -- */

	ilen = initrd_cpio_len;
	if (ilen == 0)
		return fail(EFI_LOAD_ERROR, L"embedded initrd is empty");
	status = alloc_pages(EfiLoaderData, (UINTN)ilen, 0x7fff0000ULL, (VOID **)&ibuf);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate initrd memory");
	memcpy(ibuf, initrd_cpio, (UINTN)ilen);

	/* -- boot_params -- */

	status = alloc_pages(EfiLoaderData, sizeof(*params), 0xffffffffULL, (VOID **)&params);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate boot params");
	memset(params, 0, sizeof(*params));

	/* only the setup header bytes the kernel advertises carry meaning */
	{
		UINTN hdr_len = 0x11 + hdr.setup_size;

		if (hdr_len > sizeof(struct SetupHeader))
			hdr_len = sizeof(struct SetupHeader);
		memcpy(&params->hdr, kbuf + SETUP_HDR_OFFSET, hdr_len);
	}
	params->hdr.type_of_loader = 0xff;
	params->hdr.code32_start = (UINT32)(UINTN)(kbuf + setup_total);	/* 32-bit entry */
	params->hdr.ramdisk_image = (UINT32)(UINTN)ibuf;
	params->hdr.ramdisk_size = (UINT32)ilen;
	params->ext_ramdisk_image = (UINT32)((UINT64)(UINTN)ibuf >> 32);
	params->ext_ramdisk_size = (UINT32)(ilen >> 32);

	cmd = (CHAR16 *)0;
	status = alloc_pages(EfiLoaderData, sizeof(KERNEL_CMDLINE), 0xa0000ULL, (VOID **)&cmd);
	if (EFI_ERROR(status))
		status = alloc_pages(EfiLoaderData, sizeof(KERNEL_CMDLINE), 0xffffffffULL,
				    (VOID **)&cmd);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate the command line");
	memcpy(cmd, KERNEL_CMDLINE, sizeof(KERNEL_CMDLINE));
	params->hdr.cmd_line_ptr = (UINT32)(UINTN)cmd;
	params->ext_cmd_line_ptr = (UINT32)((UINT64)(UINTN)cmd >> 32);

	print(L"efiboot: initrd ");
	print_dec(ilen);
	print(L" bytes, booting\r\n");

	/*
	 * EFI handover entry: 32-bit handover_offset from the start of the
	 * protected-mode code and another 0x200 for the 64-bit entry.  The
	 * kernel's EFI stub takes over from here (interrupts must be off).
	 */
	addr = (EFI_PHYSICAL_ADDRESS)(UINTN)kbuf + setup_total;
	handover = (handover_fn)(UINTN)(addr + 0x200 + hdr.handover_offset);
	__asm__ volatile ("cli");
	handover(image, ST, params);
	return EFI_LOAD_ERROR;	/* not reached */
}
