/*
 * efiboot.c - minimal self-contained EFI bootloader for the MikroTik boot kit
 *
 * On every boot the loader reads \BOOTKIT.CFG from the root of the partition
 * it was booted from.  The config names the EFI system partition where
 * RouterOS is installed (by the HD() device path identity: signature, start,
 * size, so it survives the device being plugged into another port); the loader
 * finds that partition, loads \EFI\BOOT\BOOTX64.EFI from it and enters the
 * kernel through the x86 EFI handover protocol.  The initramfs (initrd_so.h,
 * generated by build.sh) is embedded in the loader image.
 *
 * If the config is missing or invalid, the loader runs its install menu:
 *
 *   1) it lists the EFI partitions and asks where RouterOS is installed;
 *   2) it asks for the mode:
 *        direct    - copy the loader to the target as \EFI\BOOT\BOOTKIT.EFI,
 *                    write \BOOTKIT.CFG there and create the Boot#### entry;
 *        removable - keep the loader where it is (e.g. a USB stick) and write
 *                    \BOOTKIT.CFG next to it, pointing at the target; nothing
 *                    is copied and no boot entry is created.
 *
 *   \EFI\BOOT\BOOTKIT.EFI   this loader (direct install)
 *   \EFI\BOOT\BOOTX64.EFI   stock RouterOS kernel (EFI-stub bzImage)
 *   \BOOTKIT.CFG            target ESP identity (+ device path in a comment)
 *
 * The handover protocol (Documentation/x86/boot.rst) is used instead of the
 * raw 32/64-bit boot protocol on purpose: the entry point is the kernel's own
 * EFI stub, which preserves the EFI runtime environment (efi_info, memory map,
 * setup_graphics, ...) that the RouterOS init relies on.  The loader only has
 * to set up a struct boot_params and call the handover entry; the stub
 * relocates the kernel to its preferred address, exits boot services and
 * jumps into the decompressor.
 *
 * Build: ./build.sh -> bootkit.efi
 *   clang --target=x86_64-unknown-windows (PE32+, subsystem 10), freestanding,
 *   no libc, no gnu-efi.
 */

/* ---- configuration (compile-time) -------------------------------------- */

#define KERNEL_PATH	L"\\EFI\\BOOT\\BOOTX64.EFI"
#define CONFIG_PATH	L"\\BOOTKIT.CFG"
#define KERNEL_CMDLINE	"console=ttyS0,115200n8 rdinit=/ptrace_init"

/* the initramfs (cpio with /ptrace_init), embedded by build.sh */
#include "initrd_so.h"

/* ---- EFI essentials (self-contained subset) ---------------------------- */

typedef unsigned char		UINT8;
typedef unsigned short		UINT16;
typedef unsigned int		UINT32;
typedef unsigned long long	UINT64;
typedef signed short		INT16;
typedef signed long long	INT64;
typedef unsigned long long	UINTN;	/* LLP64: long is 32-bit on Windows targets */
typedef UINT16			CHAR16;
typedef UINT8			BOOLEAN;
typedef void			VOID;

#define TRUE 1
#define FALSE 0

#define EFIAPI __attribute__((ms_abi))
#define EFI_PAGE_SIZE 4096
#define EFI_SIZE_TO_PAGES(n) (((n) + EFI_PAGE_SIZE - 1) / EFI_PAGE_SIZE)

typedef UINTN EFI_STATUS;
typedef VOID *EFI_HANDLE;
typedef VOID *EFI_EVENT;
typedef UINT64 EFI_PHYSICAL_ADDRESS;
typedef UINT64 EFI_VIRTUAL_ADDRESS;
typedef UINTN EFI_TPL;

#define EFI_ERROR(s) ((INT64)(s) < 0)
#define EFI_SUCCESS		0
#define EFI_LOAD_ERROR		(1ULL | (1ULL << 63))
#define EFI_INVALID_PARAMETER	(2ULL | (1ULL << 63))
#define EFI_UNSUPPORTED		(3ULL | (1ULL << 63))
#define EFI_BUFFER_TOO_SMALL	(5ULL | (1ULL << 63))
#define EFI_DEVICE_ERROR	(7ULL | (1ULL << 63))
#define EFI_OUT_OF_RESOURCES	(9ULL | (1ULL << 63))
#define EFI_NOT_FOUND		(14ULL | (1ULL << 63))
#define EFI_ABORTED		(21ULL | (1ULL << 63))

#define EFI_FILE_MODE_READ	0x0000000000000001ULL
#define EFI_FILE_MODE_WRITE	0x0000000000000002ULL
#define EFI_FILE_MODE_CREATE	0x8000000000000000ULL
#define EFI_FILE_DIRECTORY	0x0000000000000010ULL

#define EFI_VARIABLE_NON_VOLATILE	0x00000001
#define EFI_VARIABLE_BOOTSERVICE_ACCESS	0x00000002
#define EFI_VARIABLE_RUNTIME_ACCESS	0x00000004
#define EFI_LOAD_OPTION_ACTIVE		0x00000001

#define EfiResetCold		0

typedef enum {
	AllocateAnyPages = 0,
	AllocateMaxAddress = 1,
	AllocateAddress = 2
} EFI_ALLOCATE_TYPE;

typedef enum {
	EfiReservedMemoryType = 0,
	EfiLoaderCode = 1,
	EfiLoaderData = 2,
	EfiBootServicesCode = 3,
	EfiBootServicesData = 4,
	EfiRuntimeServicesCode = 5,
	EfiRuntimeServicesData = 6,
	EfiConventionalMemory = 7
} EFI_MEMORY_TYPE;

typedef struct {
	UINT32 Data1;
	UINT16 Data2;
	UINT16 Data3;
	UINT8 Data4[8];
} EFI_GUID;

typedef struct {
	UINT64 Signature;
	UINT32 Revision;
	UINT32 HeaderSize;
	UINT32 CRC32;
	UINT32 Reserved;
} EFI_TABLE_HEADER;

typedef struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;
struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL {
	EFI_STATUS (EFIAPI *Reset)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, BOOLEAN);
	EFI_STATUS (EFIAPI *OutputString)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, CHAR16 *);
	EFI_STATUS (EFIAPI *TestString)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, CHAR16 *);
	EFI_STATUS (EFIAPI *QueryMode)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN, UINTN *, UINTN *);
	EFI_STATUS (EFIAPI *SetMode)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN);
	EFI_STATUS (EFIAPI *SetAttribute)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN);
	EFI_STATUS (EFIAPI *ClearScreen)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *);
	EFI_STATUS (EFIAPI *SetCursorPosition)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, UINTN, UINTN);
	EFI_STATUS (EFIAPI *EnableCursor)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *, BOOLEAN);
	VOID *Mode;
};

typedef struct {
	UINT16 ScanCode;
	CHAR16 UnicodeChar;
} EFI_INPUT_KEY;

typedef struct EFI_SIMPLE_TEXT_INPUT_PROTOCOL EFI_SIMPLE_TEXT_INPUT_PROTOCOL;
struct EFI_SIMPLE_TEXT_INPUT_PROTOCOL {
	EFI_STATUS (EFIAPI *Reset)(EFI_SIMPLE_TEXT_INPUT_PROTOCOL *, BOOLEAN);
	EFI_STATUS (EFIAPI *ReadKeyStroke)(EFI_SIMPLE_TEXT_INPUT_PROTOCOL *, EFI_INPUT_KEY *);
	EFI_EVENT WaitForKey;
};

typedef struct EFI_RUNTIME_SERVICES EFI_RUNTIME_SERVICES;
struct EFI_RUNTIME_SERVICES {
	EFI_TABLE_HEADER Hdr;
	VOID *GetTime;
	VOID *SetTime;
	VOID *GetWakeupTime;
	VOID *SetWakeupTime;
	VOID *SetVirtualAddressMap;
	VOID *ConvertPointer;
	EFI_STATUS (EFIAPI *GetVariable)(CHAR16 *, EFI_GUID *, UINT32 *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *GetNextVariableName)(UINTN *, CHAR16 *, EFI_GUID *);
	EFI_STATUS (EFIAPI *SetVariable)(CHAR16 *, EFI_GUID *, UINT32, UINTN, VOID *);
	VOID *GetNextHighMonotonicCount;
	VOID (EFIAPI *ResetSystem)(UINT32, EFI_STATUS, UINTN, VOID *);
	VOID *UpdateCapsule;
	VOID *QueryCapsuleCapabilities;
	VOID *QueryVariableInfo;
};

typedef struct EFI_BOOT_SERVICES EFI_BOOT_SERVICES;
struct EFI_BOOT_SERVICES {
	EFI_TABLE_HEADER Hdr;
	EFI_TPL (EFIAPI *RaiseTPL)(EFI_TPL);
	VOID (EFIAPI *RestoreTPL)(EFI_TPL);
	EFI_STATUS (EFIAPI *AllocatePages)(EFI_ALLOCATE_TYPE, EFI_MEMORY_TYPE, UINTN,
					   EFI_PHYSICAL_ADDRESS *);
	EFI_STATUS (EFIAPI *FreePages)(EFI_PHYSICAL_ADDRESS, UINTN);
	EFI_STATUS (EFIAPI *GetMemoryMap)(UINTN *, VOID *, UINTN *, UINTN *, UINT32 *);
	EFI_STATUS (EFIAPI *AllocatePool)(EFI_MEMORY_TYPE, UINTN, VOID **);
	EFI_STATUS (EFIAPI *FreePool)(VOID *);
	VOID *CreateEvent;
	VOID *SetTimer;
	VOID *WaitForEvent;
	VOID *SignalEvent;
	VOID *CloseEvent;
	VOID *CheckEvent;
	VOID *InstallProtocolInterface;
	VOID *ReinstallProtocolInterface;
	VOID *UninstallProtocolInterface;
	EFI_STATUS (EFIAPI *HandleProtocol)(EFI_HANDLE, EFI_GUID *, VOID **);
	VOID *Reserved;
	VOID *RegisterProtocolNotify;
	VOID *LocateHandle;
	VOID *LocateDevicePath;
	VOID *InstallConfigurationTable;
	VOID *LoadImage;
	VOID *StartImage;
	VOID *Exit;
	VOID *UnloadImage;
	VOID *ExitBootServices;
	VOID *GetNextMonotonicCount;
	EFI_STATUS (EFIAPI *Stall)(UINTN);
	VOID *SetWatchdogTimer;
	VOID *ConnectController;
	VOID *DisconnectController;
	VOID *OpenProtocol;
	VOID *CloseProtocol;
	VOID *OpenProtocolInformation;
	VOID *ProtocolsPerHandle;
	EFI_STATUS (EFIAPI *LocateHandleBuffer)(UINTN, EFI_GUID *, VOID *, UINTN *, EFI_HANDLE **);
	EFI_STATUS (EFIAPI *LocateProtocol)(EFI_GUID *, VOID *, VOID **);
	VOID *InstallMultipleProtocolInterfaces;
	VOID *UninstallMultipleProtocolInterfaces;
	VOID *CalculateCrc32;
	VOID *CopyMem;
	VOID *SetMem;
	VOID *CreateEventEx;
};

typedef struct {
	EFI_TABLE_HEADER Hdr;
	CHAR16 *FirmwareVendor;
	UINT32 FirmwareRevision;
	EFI_HANDLE ConsoleInHandle;
	EFI_SIMPLE_TEXT_INPUT_PROTOCOL *ConIn;
	EFI_HANDLE ConsoleOutHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *ConOut;
	EFI_HANDLE StandardErrorHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *StdErr;
	EFI_RUNTIME_SERVICES *RuntimeServices;
	EFI_BOOT_SERVICES *BootServices;
	UINTN NumberOfTableEntries;
	VOID *ConfigurationTable;
} EFI_SYSTEM_TABLE;

typedef struct {
	UINT32 Revision;
	UINT32 _pad;
	EFI_HANDLE ParentHandle;
	EFI_SYSTEM_TABLE *SystemTable;
	EFI_HANDLE DeviceHandle;
	VOID *FilePath;
	VOID *Reserved;
	UINT32 LoadOptionsSize;
	UINT32 _pad2;
	VOID *LoadOptions;
	VOID *ImageBase;
	UINT64 ImageSize;
	UINT32 ImageCodeType;
	UINT32 ImageDataType;
	VOID *Unload;
} EFI_LOADED_IMAGE_PROTOCOL;

typedef struct EFI_FILE_PROTOCOL EFI_FILE_PROTOCOL;
struct EFI_FILE_PROTOCOL {
	UINT64 Revision;
	EFI_STATUS (EFIAPI *Open)(EFI_FILE_PROTOCOL *, EFI_FILE_PROTOCOL **, CHAR16 *,
				  UINT64, UINT64);
	EFI_STATUS (EFIAPI *Close)(EFI_FILE_PROTOCOL *);
	EFI_STATUS (EFIAPI *Delete)(EFI_FILE_PROTOCOL *);
	EFI_STATUS (EFIAPI *Read)(EFI_FILE_PROTOCOL *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *Write)(EFI_FILE_PROTOCOL *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *GetPosition)(EFI_FILE_PROTOCOL *, UINT64 *);
	EFI_STATUS (EFIAPI *SetPosition)(EFI_FILE_PROTOCOL *, UINT64);
	EFI_STATUS (EFIAPI *GetInfo)(EFI_FILE_PROTOCOL *, EFI_GUID *, UINTN *, VOID *);
	EFI_STATUS (EFIAPI *SetInfo)(EFI_FILE_PROTOCOL *, EFI_GUID *, UINTN, VOID *);
	EFI_STATUS (EFIAPI *Flush)(EFI_FILE_PROTOCOL *);
	VOID *OpenEx;
	VOID *ReadEx;
	VOID *WriteEx;
	VOID *FlushEx;
};

typedef struct {
	UINT64 Revision;
	EFI_STATUS (EFIAPI *OpenVolume)(VOID *, EFI_FILE_PROTOCOL **);
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

typedef struct {
	UINT16 Year;
	UINT8 Month;
	UINT8 Day;
	UINT8 Hour;
	UINT8 Minute;
	UINT8 Second;
	UINT8 _pad1;
	UINT32 Nanosecond;
	INT16 TimeZone;
	UINT8 Daylight;
	UINT8 _pad2;
} EFI_TIME;

typedef struct {
	UINT64 Size;
	UINT64 FileSize;
	UINT64 PhysicalSize;
	EFI_TIME CreationTime;
	EFI_TIME LastAccessTime;
	EFI_TIME ModificationTime;
	UINT64 Attribute;
	CHAR16 FileName[1];
} EFI_FILE_INFO;

typedef struct {
	UINT64 Size;
	BOOLEAN ReadOnly;
	UINT64 VolumeSize;
	UINT64 FreeSpace;
	UINT32 BlockSize;
	CHAR16 VolumeLabel[1];
} EFI_FILE_SYSTEM_INFO;

typedef struct {
	UINT8 Type;
	UINT8 SubType;
	UINT8 Length[2];
} __attribute__((packed)) EFI_DEVICE_PATH_PROTOCOL;

typedef struct {
	EFI_DEVICE_PATH_PROTOCOL Header;
	UINT32 PartitionNumber;
	UINT64 PartitionStart;
	UINT64 PartitionSize;
	UINT8 Signature[16];
	UINT8 MBRType;
	UINT8 SignatureType;
} __attribute__((packed)) HARDDRIVE_DEVICE_PATH;

typedef struct {
	CHAR16 *(EFIAPI *ConvertDeviceNodeToText)(EFI_DEVICE_PATH_PROTOCOL *, BOOLEAN, BOOLEAN);
	CHAR16 *(EFIAPI *ConvertDevicePathToText)(EFI_DEVICE_PATH_PROTOCOL *, BOOLEAN, BOOLEAN);
} EFI_DEVICE_PATH_TO_TEXT_PROTOCOL;

#define EFI_BY_PROTOCOL 2
#define EFI_DEVICE_PATH_TYPE_MEDIA 0x04
#define EFI_DEVICE_PATH_SUBTYPE_HARDDRIVE 0x01
#define EFI_DEVICE_PATH_SUBTYPE_FILEPATH 0x04
#define EFI_DEVICE_PATH_TYPE_END 0x7f
#define EFI_DEVICE_PATH_SUBTYPE_END_ENTIRE 0xff
#define EFI_HD_SIGNATURE_MBR 0x01
#define EFI_HD_SIGNATURE_GPT 0x02

#define EFI_FILE_MODE_READ 0x0000000000000001ULL

static EFI_GUID loaded_image_protocol_guid = {
	0x5b1b31a1, 0x9562, 0x11d2, { 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID simple_file_system_guid = {
	0x0964e5b22, 0x6459, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID file_info_guid = {
	0x09576e92, 0x6d3f, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID file_system_info_guid = {
	0x09576e93, 0x6d3f, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID device_path_guid = {
	0x09576e91, 0x6d3f, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
};
static EFI_GUID device_path_to_text_guid = {
	0x8b843e20, 0x8132, 0x4852, { 0x90, 0xcc, 0x55, 0x1a, 0x4e, 0x4a, 0x7f, 0x1c }
};
static EFI_GUID global_variable_guid = {
	0x8be4df61, 0x93ca, 0x11d2, { 0xaa, 0x0d, 0x00, 0xe0, 0x98, 0x03, 0x2b, 0x8c }
};

/* ---- x86 boot protocol structures -------------------------------------- */

struct SetupHeader {
	UINT8 setup_sects;
	UINT16 root_flags;
	UINT32 syssize;
	UINT16 ram_size;
	UINT16 vid_mode;
	UINT16 root_dev;
	UINT16 boot_flag;
	UINT8 jump;
	UINT8 setup_size;
	UINT32 header;
	UINT16 version;
	UINT32 realmode_swtch;
	UINT16 start_sys_seg;
	UINT16 kernel_version;
	UINT8 type_of_loader;
	UINT8 loadflags;
	UINT16 setup_move_size;
	UINT32 code32_start;
	UINT32 ramdisk_image;
	UINT32 ramdisk_size;
	UINT32 bootsect_kludge;
	UINT16 heap_end_ptr;
	UINT8 ext_loader_ver;
	UINT8 ext_loader_type;
	UINT32 cmd_line_ptr;
	UINT32 initrd_addr_max;
	UINT32 kernel_alignment;
	UINT8 relocatable_kernel;
	UINT8 min_alignment;
	UINT16 xloadflags;
	UINT32 cmdline_size;
	UINT32 hardware_subarch;
	UINT64 hardware_subarch_data;
	UINT32 payload_offset;
	UINT32 payload_length;
	UINT64 setup_data;
	UINT64 pref_address;
	UINT32 init_size;
	UINT32 handover_offset;
	UINT32 kernel_info_offset;
} __attribute__((packed));

#define SETUP_HDR_OFFSET	0x1f1
#define SETUP_HDR_MAGIC		0x53726448	/* "HdrS" */
#define BOOT_FLAG_MAGIC		0xaa55
#define SETUP_VERSION_2_11	0x20b
#define SETUP_VERSION_2_12	0x20c

#define XLF_KERNEL_64			(1 << 0)
#define XLF_CAN_BE_LOADED_ABOVE_4G	(1 << 1)
#define XLF_EFI_HANDOVER_32		(1 << 2)
#define XLF_EFI_HANDOVER_64		(1 << 3)

struct BootParams {
	UINT8 _pad0[0xc0];
	UINT32 ext_ramdisk_image;
	UINT32 ext_ramdisk_size;
	UINT32 ext_cmd_line_ptr;
	UINT8 _pad1[SETUP_HDR_OFFSET - 0xcc];
	struct SetupHeader hdr;
	UINT8 _pad2[4096 - SETUP_HDR_OFFSET - sizeof(struct SetupHeader)];
} __attribute__((packed));

_Static_assert(__builtin_offsetof(struct BootParams, ext_ramdisk_image) == 0xc0, "boot_params layout");
_Static_assert(__builtin_offsetof(struct BootParams, ext_cmd_line_ptr) == 0xc8, "boot_params layout");
_Static_assert(__builtin_offsetof(struct BootParams, hdr) == SETUP_HDR_OFFSET, "boot_params layout");
_Static_assert(sizeof(struct BootParams) == 4096, "boot_params layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, header) == 0x11, "setup header layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, code32_start) == 0x23, "setup header layout");
_Static_assert(__builtin_offsetof(struct SetupHeader, handover_offset) == 0x73, "setup header layout");

/* the handover entry point is kernel code: SysV ABI, not the EFI ABI */
typedef void (*handover_fn)(VOID *handle, EFI_SYSTEM_TABLE *st,
			    struct BootParams *params) __attribute__((sysv_abi));

/* ---- runtime helpers --------------------------------------------------- */

static EFI_SYSTEM_TABLE *ST;
static EFI_BOOT_SERVICES *BS;
static EFI_RUNTIME_SERVICES *RS;

/* kept out of efi_main's stack frame: >4 KiB frames need a __chkstk probe */
static UINT8 first_page[4096];

/*
 * The image is fully position independent, so without this the linker would
 * emit no base relocations at all and firmware could not load the image
 * anywhere but its preferred base (0x140000000).  One self-referencing
 * pointer forces a .reloc section.
 */
static const VOID *const force_relocation __attribute__((used)) = &force_relocation;

/*
 * clang may turn bulk copies/clears into mem*() calls; keep the definitions
 * local and stop the compiler from re-recognising the loops as builtins.
 */
__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memcpy(VOID *dst, const VOID *src, UINTN n)
{
	UINT8 *d = dst;
	const UINT8 *s = src;

	while (n--)
		*d++ = *s++;
	return dst;
}

__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memmove(VOID *dst, const VOID *src, UINTN n)
{
	UINT8 *d = dst;
	const UINT8 *s = src;

	if (d < s)
		while (n--)
			*d++ = *s++;
	else {
		d += n;
		s += n;
		while (n--)
			*--d = *--s;
	}
	return dst;
}

__attribute__((no_builtin("memcpy", "memmove", "memset")))
VOID *memset(VOID *dst, int c, UINTN n)
{
	UINT8 *d = dst;

	while (n--)
		*d++ = (UINT8)c;
	return dst;
}

__attribute__((no_builtin("memcmp")))
int memcmp(const VOID *a, const VOID *b, UINTN n)
{
	const UINT8 *p = a, *q = b;

	while (n--) {
		if (*p != *q)
			return (int)*p - (int)*q;
		p++;
		q++;
	}
	return 0;
}

static VOID print(CHAR16 *s)
{
	ST->ConOut->OutputString(ST->ConOut, s);
}

static VOID print_hex(UINT64 v)
{
	static const CHAR16 digits[] = L"0123456789abcdef";
	CHAR16 buf[19];
	UINTN i;

	buf[0] = L'0';
	buf[1] = L'x';
	for (i = 0; i < 16; i++)
		buf[2 + i] = digits[(v >> ((15 - i) * 4)) & 0xf];
	buf[18] = 0;
	print(buf);
}

static VOID print_dec(UINT64 v)
{
	CHAR16 buf[21];
	UINTN i = 20;

	buf[i] = 0;
	if (!v)
		buf[--i] = L'0';
	while (v) {
		buf[--i] = (CHAR16)(L'0' + v % 10);
		v /= 10;
	}
	print(buf + i);
}

static EFI_STATUS fail(EFI_STATUS status, CHAR16 *msg)
{
	print(L"efiboot: ");
	print(msg);
	print(L" (status ");
	print_hex(status);
	print(L")\r\n");
	BS->Stall(5000000);
	return status;
}

/* ---- file access ------------------------------------------------------- */

static EFI_STATUS open_root(EFI_HANDLE image, EFI_FILE_PROTOCOL **root)
{
	EFI_LOADED_IMAGE_PROTOCOL *li;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
	EFI_STATUS status;

	status = BS->HandleProtocol(image, &loaded_image_protocol_guid, (VOID **)&li);
	if (EFI_ERROR(status))
		return status;
	status = BS->HandleProtocol(li->DeviceHandle, &simple_file_system_guid, (VOID **)&fs);
	if (EFI_ERROR(status))
		return status;
	return fs->OpenVolume(fs, root);
}

static EFI_STATUS open_file(EFI_FILE_PROTOCOL *root, CHAR16 *path, EFI_FILE_PROTOCOL **f)
{
	return root->Open(root, f, path, EFI_FILE_MODE_READ, 0);
}

static EFI_STATUS file_size(EFI_FILE_PROTOCOL *f, UINT64 *size)
{
	EFI_FILE_INFO *info;
	EFI_STATUS status;
	UINTN buf_size = 560;
	UINT8 buf[560];

	status = f->GetInfo(f, &file_info_guid, &buf_size, buf);
	if (EFI_ERROR(status))
		return status;
	info = (EFI_FILE_INFO *)buf;
	*size = info->FileSize;
	return EFI_SUCCESS;
}

/* read [off, off+len) into buf; the buffer must be large enough */
static EFI_STATUS read_file(EFI_FILE_PROTOCOL *f, UINT64 off, VOID *buf, UINTN len)
{
	EFI_STATUS status;
	UINT8 *p = buf;

	status = f->SetPosition(f, off);
	if (EFI_ERROR(status))
		return status;
	while (len) {
		UINTN n = len;

		status = f->Read(f, &n, p);
		if (EFI_ERROR(status))
			return status;
		if (n == 0)
			return EFI_LOAD_ERROR;	/* short file */
		p += n;
		len -= n;
	}
	return EFI_SUCCESS;
}

static EFI_STATUS alloc_pages(EFI_MEMORY_TYPE type, UINTN size,
			      EFI_PHYSICAL_ADDRESS max_addr, VOID **out)
{
	EFI_PHYSICAL_ADDRESS addr = max_addr;
	EFI_STATUS status;

	status = BS->AllocatePages(AllocateMaxAddress, type,
				   EFI_SIZE_TO_PAGES(size), &addr);
	if (EFI_ERROR(status))
		return status;
	*out = (VOID *)(UINTN)addr;
	return EFI_SUCCESS;
}

/* ---- installer mode ---------------------------------------------------- */

static VOID print_ch(CHAR16 ch)
{
	CHAR16 buf[2];

	buf[0] = ch;
	buf[1] = 0;
	print(buf);
}

static VOID print_hex4(UINT16 v)
{
	static const CHAR16 digits[] = L"0123456789abcdef";
	CHAR16 buf[5];
	UINTN i;

	for (i = 0; i < 4; i++)
		buf[i] = digits[(v >> ((3 - i) * 4)) & 0xf];
	buf[4] = 0;
	print(buf);
}

static VOID boot_var_name(CHAR16 *name, UINT16 index)
{
	static const CHAR16 digits[] = L"0123456789ABCDEF";

	name[0] = L'B';
	name[1] = L'o';
	name[2] = L'o';
	name[3] = L't';
	name[4] = digits[(index >> 12) & 0xf];
	name[5] = digits[(index >> 8) & 0xf];
	name[6] = digits[(index >> 4) & 0xf];
	name[7] = digits[index & 0xf];
	name[8] = 0;
}

static UINTN str_len16(const CHAR16 *s)
{
	UINTN n = 0;

	while (s[n])
		n++;
	return n;
}

static BOOLEAN chr_equal_ci(CHAR16 a, CHAR16 b)
{
	if (a >= L'a' && a <= L'z')
		a -= 32;
	if (b >= L'a' && b <= L'z')
		b -= 32;
	return a == b;
}

static BOOLEAN str_equal_ci(const CHAR16 *a, const CHAR16 *b)
{
	while (*a && *b) {
		if (!chr_equal_ci(*a, *b))
			return FALSE;
		a++;
		b++;
	}
	return *a == *b;
}

/* does a (possibly unterminated) LoadOptions string contain token? */
static BOOLEAN load_options_have(EFI_LOADED_IMAGE_PROTOCOL *li, const CHAR16 *token)
{
	UINTN i, n = li->LoadOptionsSize / sizeof(CHAR16);
	CHAR16 *opt = li->LoadOptions;

	if (!opt)
		return FALSE;
	for (i = 0; i + str_len16(token) <= n; i++) {
		if (str_equal_ci(opt + i, token))
			return TRUE;
	}
	return FALSE;
}

static UINTN dp_node_len(EFI_DEVICE_PATH_PROTOCOL *node)
{
	return (UINTN)node->Length[0] | ((UINTN)node->Length[1] << 8);
}

static BOOLEAN dp_is_end(EFI_DEVICE_PATH_PROTOCOL *node)
{
	return node->Type == EFI_DEVICE_PATH_TYPE_END &&
	       node->SubType == EFI_DEVICE_PATH_SUBTYPE_END_ENTIRE;
}

static EFI_DEVICE_PATH_PROTOCOL *dp_next(EFI_DEVICE_PATH_PROTOCOL *node)
{
	return (EFI_DEVICE_PATH_PROTOCOL *)((UINT8 *)node + dp_node_len(node));
}

static BOOLEAN dp_is_filepath(EFI_DEVICE_PATH_PROTOCOL *node)
{
	return node->Type == EFI_DEVICE_PATH_TYPE_MEDIA &&
	       node->SubType == EFI_DEVICE_PATH_SUBTYPE_FILEPATH;
}

/* length of all nodes up to (not including) the end node */
static UINTN dp_nodes_len(EFI_DEVICE_PATH_PROTOCOL *dp)
{
	UINTN len = 0;

	while (!dp_is_end(dp)) {
		len += dp_node_len(dp);
		dp = dp_next(dp);
	}
	return len;
}

/* file path of our own loaded image (e.g. \EFI\BOOT\BOOTKIT.EFI) */
static EFI_STATUS self_file_path(EFI_LOADED_IMAGE_PROTOCOL *li, CHAR16 **path)
{
	EFI_DEVICE_PATH_PROTOCOL *node = li->FilePath, *fp = 0;

	if (!node)
		return EFI_NOT_FOUND;
	while (!dp_is_end(node)) {
		if (dp_is_filepath(node))
			fp = node;
		node = dp_next(node);
	}
	if (!fp)
		return EFI_NOT_FOUND;
	*path = (CHAR16 *)((UINT8 *)fp + 4);
	return EFI_SUCCESS;
}

/* ---- configuration ----------------------------------------------------- */

/*
 * Identity of an EFI system partition: the fields of its HD() device path
 * node.  Bus topology is deliberately not part of it, so the same partition is
 * found again when the disk is plugged into another port.
 */
typedef struct {
	UINT8 type;		/* EFI_HD_SIGNATURE_MBR or _GPT */
	UINT8 sig[16];		/* 4 bytes for MBR, 16 for GPT */
	UINT64 start;		/* partition start, 512-byte blocks */
	UINT64 size;		/* partition size, 512-byte blocks */
} TARGET_ID;

#define CONFIG_MAX 512

static BOOLEAN dp_is_harddrive(EFI_DEVICE_PATH_PROTOCOL *node)
{
	return node->Type == EFI_DEVICE_PATH_TYPE_MEDIA &&
	       node->SubType == EFI_DEVICE_PATH_SUBTYPE_HARDDRIVE;
}

static BOOLEAN target_id_from_dp(EFI_DEVICE_PATH_PROTOCOL *dp, TARGET_ID *id)
{
	while (!dp_is_end(dp)) {
		if (dp_is_harddrive(dp)) {
			HARDDRIVE_DEVICE_PATH *hd = (HARDDRIVE_DEVICE_PATH *)dp;

			memset(id, 0, sizeof(*id));
			id->type = hd->SignatureType;
			memcpy(id->sig, hd->Signature, sizeof(id->sig));
			id->start = hd->PartitionStart;
			id->size = hd->PartitionSize;
			return id->type == EFI_HD_SIGNATURE_MBR ||
			       id->type == EFI_HD_SIGNATURE_GPT;
		}
		dp = dp_next(dp);
	}
	return FALSE;
}

static BOOLEAN target_id_equal(const TARGET_ID *a, const TARGET_ID *b)
{
	UINTN sig_len;

	if (a->type != b->type || a->start != b->start || a->size != b->size)
		return FALSE;
	sig_len = a->type == EFI_HD_SIGNATURE_GPT ? 16 : 4;
	return memcmp(a->sig, b->sig, sig_len) == 0;
}

static int hex_digit(char c)
{
	if (c >= '0' && c <= '9')
		return c - '0';
	if (c >= 'a' && c <= 'f')
		return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
		return c - 'A' + 10;
	return -1;
}

static BOOLEAN hex_u64(const char **ps, const char *end, UINT64 *out)
{
	const char *p = *ps;
	UINT64 v = 0;
	UINTN digits = 0;

	while (p < end) {
		int d = hex_digit(*p);

		if (d < 0)
			break;
		v = (v << 4) | (UINTN)d;
		digits++;
		p++;
	}
	if (!digits)
		return FALSE;
	*ps = p;
	*out = v;
	return TRUE;
}

static BOOLEAN parse_target_id(const char *s, UINTN len, TARGET_ID *id)
{
	const char *p = s, *end = s + len;
	UINTN sig_len, i;

	memset(id, 0, sizeof(*id));
	if (len >= 4 && (s[0] == 'm' || s[0] == 'M') &&
	    (s[1] == 'b' || s[1] == 'B') && (s[2] == 'r' || s[2] == 'R') && s[3] == ':') {
		id->type = EFI_HD_SIGNATURE_MBR;
		sig_len = 4;
		p += 4;
	} else if (len >= 4 && (s[0] == 'g' || s[0] == 'G') &&
		   (s[1] == 'p' || s[1] == 'P') && (s[2] == 't' || s[2] == 'T') && s[3] == ':') {
		id->type = EFI_HD_SIGNATURE_GPT;
		sig_len = 16;
		p += 4;
	} else {
		return FALSE;
	}
	if ((UINTN)(end - p) < sig_len * 2)
		return FALSE;
	for (i = 0; i < sig_len; i++) {
		int hi = hex_digit(p[0]), lo = hex_digit(p[1]);

		if (hi < 0 || lo < 0)
			return FALSE;
		id->sig[i] = (UINT8)((hi << 4) | lo);
		p += 2;
	}
	if (p >= end || *p != ':')
		return FALSE;
	p++;
	if (!hex_u64(&p, end, &id->start))
		return FALSE;
	if (p >= end || *p != ':')
		return FALSE;
	p++;
	if (!hex_u64(&p, end, &id->size))
		return FALSE;
	if (p != end || id->size == 0)
		return FALSE;
	return TRUE;
}

static BOOLEAN config_parse(const char *buf, UINTN len, TARGET_ID *id)
{
	UINTN i = 0;

	while (i < len) {
		UINTN start = i, end;

		while (i < len && buf[i] != '\n' && buf[i] != '\r')
			i++;
		end = i;
		while (i < len && (buf[i] == '\n' || buf[i] == '\r'))
			i++;
		while (start < end && (buf[start] == ' ' || buf[start] == '\t'))
			start++;
		while (end > start && (buf[end - 1] == ' ' || buf[end - 1] == '\t'))
			end--;
		if (start == end || buf[start] == '#')
			continue;
		if (end - start >= 7 &&
		    (buf[start] == 't' || buf[start] == 'T') &&
		    (buf[start + 1] == 'a' || buf[start + 1] == 'A') &&
		    (buf[start + 2] == 'r' || buf[start + 2] == 'R') &&
		    (buf[start + 3] == 'g' || buf[start + 3] == 'G') &&
		    (buf[start + 4] == 'e' || buf[start + 4] == 'E') &&
		    (buf[start + 5] == 't' || buf[start + 5] == 'T') &&
		    buf[start + 6] == '=') {
			if (parse_target_id(buf + start + 7, end - start - 7, id))
				return TRUE;
		}
	}
	return FALSE;
}

static EFI_STATUS config_read(EFI_FILE_PROTOCOL *root, TARGET_ID *id)
{
	EFI_FILE_PROTOCOL *f;
	EFI_STATUS status;
	UINT64 size;
	char buf[CONFIG_MAX + 1];
	UINTN len;

	status = root->Open(root, &f, CONFIG_PATH, EFI_FILE_MODE_READ, 0);
	if (EFI_ERROR(status))
		return status;
	status = file_size(f, &size);
	if (EFI_ERROR(status)) {
		f->Close(f);
		return status;
	}
	len = (UINTN)(size > CONFIG_MAX ? CONFIG_MAX : size);
	status = read_file(f, 0, buf, len);
	f->Close(f);
	if (EFI_ERROR(status))
		return status;
	buf[len] = 0;
	if (!config_parse(buf, len, id))
		return EFI_INVALID_PARAMETER;
	return EFI_SUCCESS;
}

static UINTN c_append(char *buf, UINTN cap, UINTN pos, const char *s, UINTN len)
{
	if (pos >= cap - 1)
		return pos;
	if (len > cap - 1 - pos)
		len = cap - 1 - pos;
	memcpy(buf + pos, s, len);
	return pos + len;
}

static UINTN c_append_hex_u64(char *buf, UINTN cap, UINTN pos, UINT64 v)
{
	static const char digits[] = "0123456789abcdef";
	char tmp[16];
	UINTN n = 0;

	if (!v)
		tmp[n++] = '0';
	while (v) {
		tmp[n++] = digits[v & 0xf];
		v >>= 4;
	}
	while (n && pos < cap - 1)
		buf[pos++] = tmp[--n];
	return pos;
}

static UINTN fmt_target_id(char *buf, UINTN cap, const TARGET_ID *id)
{
	static const char digits[] = "0123456789abcdef";
	const char *type = id->type == EFI_HD_SIGNATURE_GPT ? "gpt" : "mbr";
	UINTN sig_len = id->type == EFI_HD_SIGNATURE_GPT ? 16 : 4;
	UINTN pos = 0, i;

	pos = c_append(buf, cap, pos, type, 3);
	buf[pos++] = ':';
	for (i = 0; i < sig_len; i++) {
		buf[pos++] = digits[id->sig[i] >> 4];
		buf[pos++] = digits[id->sig[i] & 0xf];
	}
	buf[pos++] = ':';
	pos = c_append_hex_u64(buf, cap, pos, id->start);
	buf[pos++] = ':';
	pos = c_append_hex_u64(buf, cap, pos, id->size);
	return pos;
}

static EFI_STATUS write_file(EFI_FILE_PROTOCOL *root, CHAR16 *path, VOID *data, UINTN len)
{
	EFI_FILE_PROTOCOL *f;
	EFI_STATUS status;
	UINTN written = len;
	UINT8 fi_buf[sizeof(EFI_FILE_INFO) + 8];
	EFI_FILE_INFO *fi = (EFI_FILE_INFO *)fi_buf;

	status = root->Open(root, &f, path,
			    EFI_FILE_MODE_READ | EFI_FILE_MODE_WRITE | EFI_FILE_MODE_CREATE, 0);
	if (EFI_ERROR(status))
		return status;
	memset(fi_buf, 0, sizeof(fi_buf));
	fi->Size = sizeof(EFI_FILE_INFO) + 2;
	fi->FileSize = 0;
	f->SetInfo(f, &file_info_guid, sizeof(EFI_FILE_INFO) + 2, fi_buf);
	status = f->Write(f, &written, data);
	f->Flush(f);
	f->Close(f);
	if (EFI_ERROR(status))
		return status;
	if (written != len)
		return EFI_DEVICE_ERROR;
	return EFI_SUCCESS;
}

static EFI_STATUS config_write(EFI_FILE_PROTOCOL *root, const TARGET_ID *id,
			       EFI_DEVICE_PATH_PROTOCOL *dp)
{
	EFI_DEVICE_PATH_TO_TEXT_PROTOCOL *d2t = 0;
	char buf[CONFIG_MAX];
	UINTN pos = 0;

	pos = c_append(buf, sizeof(buf), pos, "# MikroTik boot kit\r\n", 21);
	BS->LocateProtocol(&device_path_to_text_guid, 0, (VOID **)&d2t);
	if (d2t && dp) {
		CHAR16 *text = d2t->ConvertDevicePathToText(dp, FALSE, TRUE);

		if (text) {
			pos = c_append(buf, sizeof(buf) - 3, pos, "# target ESP: ", 14);
			for (; *text && pos < sizeof(buf) - 3; text++)
				buf[pos++] = (char)*text;
			pos = c_append(buf, sizeof(buf), pos, "\r\n", 2);
		}
	}
	pos = c_append(buf, sizeof(buf), pos, "target=", 7);
	pos += fmt_target_id(buf + pos, sizeof(buf) - pos - 3, id);
	pos = c_append(buf, sizeof(buf), pos, "\r\n", 2);
	return write_file(root, CONFIG_PATH, buf, pos);
}

/* open the root of the volume whose HD() identity is id */
static EFI_STATUS find_target_root(const TARGET_ID *id, EFI_FILE_PROTOCOL **out)
{
	EFI_HANDLE *handles = 0;
	UINTN count = 0, i;
	EFI_STATUS status;

	status = BS->LocateHandleBuffer(EFI_BY_PROTOCOL, &simple_file_system_guid,
					0, &count, &handles);
	if (EFI_ERROR(status))
		return status;
	for (i = 0; i < count; i++) {
		EFI_DEVICE_PATH_PROTOCOL *dp = 0;
		EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
		TARGET_ID cur;

		if (EFI_ERROR(BS->HandleProtocol(handles[i], &device_path_guid,
						 (VOID **)&dp)))
			continue;
		if (!target_id_from_dp(dp, &cur) || !target_id_equal(&cur, id))
			continue;
		if (EFI_ERROR(BS->HandleProtocol(handles[i], &simple_file_system_guid,
						 (VOID **)&fs)))
			continue;
		if (EFI_ERROR(fs->OpenVolume(fs, out)))
			continue;
		BS->FreePool(handles);
		return EFI_SUCCESS;
	}
	BS->FreePool(handles);
	return EFI_NOT_FOUND;
}

/* device part of dp + file path node for path + end node */
static EFI_DEVICE_PATH_PROTOCOL *dp_with_file(EFI_DEVICE_PATH_PROTOCOL *dp,
					      const CHAR16 *path)
{
	UINTN dev_len = dp_nodes_len(dp);
	UINTN path_len = str_len16(path);
	UINTN fp_len = 4 + (path_len + 1) * 2, total = dev_len + fp_len + 4;
	EFI_DEVICE_PATH_PROTOCOL *full;
	UINT8 *fp;
	VOID *p = 0;

	if (EFI_ERROR(BS->AllocatePool(EfiLoaderData, total, &p)))
		return 0;
	full = p;
	memcpy(full, dp, dev_len);
	fp = (UINT8 *)full + dev_len;
	fp[0] = EFI_DEVICE_PATH_TYPE_MEDIA;
	fp[1] = EFI_DEVICE_PATH_SUBTYPE_FILEPATH;
	fp[2] = fp_len & 0xff;
	fp[3] = fp_len >> 8;
	memcpy(fp + 4, path, (path_len + 1) * 2);
	fp += fp_len;
	fp[0] = EFI_DEVICE_PATH_TYPE_END;
	fp[1] = EFI_DEVICE_PATH_SUBTYPE_END_ENTIRE;
	fp[2] = 4;
	fp[3] = 0;
	return full;
}

static VOID print_trunc(const CHAR16 *s, UINTN max)
{
	CHAR16 buf[80];
	UINTN i = 0;

	while (i < max && i < sizeof(buf) / sizeof(buf[0]) - 1 && s[i]) {
		buf[i] = s[i];
		i++;
	}
	if (s[i]) {
		buf[i++] = L'.';
		buf[i++] = L'.';
		buf[i++] = L'.';
	}
	buf[i] = 0;
	print(buf);
}

/* wait for any key (polling: no event services needed) */
static EFI_INPUT_KEY wait_key(VOID)
{
	EFI_INPUT_KEY key = { 0, 0 };

	while (EFI_ERROR(ST->ConIn->ReadKeyStroke(ST->ConIn, &key)))
		BS->Stall(20000);
	return key;
}

/* read a decimal number, terminated by Enter; q/ESC cancels */
static EFI_STATUS read_number(UINTN *out)
{
	UINTN val = 0;
	BOOLEAN any = FALSE;

	for (;;) {
		EFI_INPUT_KEY key = wait_key();

		if (key.ScanCode == 0x17 || key.UnicodeChar == L'q' ||
		    key.UnicodeChar == L'Q')
			return EFI_ABORTED;
		if (key.UnicodeChar == L'\r' || key.UnicodeChar == L'\n') {
			if (any) {
				*out = val;
				return EFI_SUCCESS;
			}
			continue;
		}
		if (key.UnicodeChar >= L'0' && key.UnicodeChar <= L'9' && val < 1000) {
			val = val * 10 + (key.UnicodeChar - L'0');
			any = TRUE;
			print_ch(key.UnicodeChar);
		} else if (key.UnicodeChar == 0x08 && any) {
			val /= 10;
			any = val != 0;
			print(L"\b \b");
		}
	}
}

static VOID *pool_alloc(UINTN size)
{
	VOID *p = 0;

	if (EFI_ERROR(BS->AllocatePool(EfiLoaderData, size, &p)))
		return 0;
	return p;
}

static VOID *pool_alloc_zero(UINTN size)
{
	VOID *p = pool_alloc(size);

	if (p)
		memset(p, 0, size);
	return p;
}

/* read a variable into a freshly allocated buffer (NULL/0 if absent/empty) */
static EFI_STATUS read_variable(CHAR16 *name, EFI_GUID *guid, UINT32 *attrs,
				VOID **data, UINTN *size)
{
	UINT8 stack[256];
	UINTN cap = sizeof(stack);
	EFI_STATUS status;

	status = RS->GetVariable(name, guid, attrs, &cap, stack);
	if (status == EFI_BUFFER_TOO_SMALL) {
		*data = pool_alloc(cap);
		if (!*data)
			return EFI_OUT_OF_RESOURCES;
		status = RS->GetVariable(name, guid, attrs, &cap, *data);
		if (EFI_ERROR(status)) {
			BS->FreePool(*data);
			*data = 0;
			return status;
		}
		*size = cap;
		return EFI_SUCCESS;
	}
	if (status == EFI_NOT_FOUND) {
		*data = 0;
		*size = 0;
		return status;
	}
	if (EFI_ERROR(status))
		return status;
	if (cap == 0) {
		*data = 0;
		*size = 0;
		return EFI_SUCCESS;
	}
	*data = pool_alloc(cap);
	if (!*data)
		return EFI_OUT_OF_RESOURCES;
	memcpy(*data, stack, cap);
	*size = cap;
	return EFI_SUCCESS;
}

static BOOLEAN boot_var_index(const CHAR16 *name, UINT16 *index)
{
	UINTN i, v = 0;

	if (str_len16(name) != 8)
		return FALSE;
	if (name[0] != L'B' || name[1] != L'o' || name[2] != L'o' || name[3] != L't')
		return FALSE;
	for (i = 4; i < 8; i++) {
		CHAR16 c = name[i];

		if (c >= L'0' && c <= L'9')
			v = v * 16 + (c - L'0');
		else if (c >= L'A' && c <= L'F')
			v = v * 16 + (c - L'A' + 10);
		else if (c >= L'a' && c <= L'f')
			v = v * 16 + (c - L'a' + 10);
		else
			return FALSE;
	}
	*index = (UINT16)v;
	return TRUE;
}

/*
 * Create (or find) the Boot#### entry for \EFI\BOOT\BOOTKIT.EFI on
 * vol_handle and put it first in BootOrder.
 */
static EFI_STATUS boot_entry_add(EFI_HANDLE vol_handle, CHAR16 *file_path)
{
	EFI_DEVICE_PATH_PROTOCOL *vol_dp = 0, *full = 0;
	EFI_STATUS status;
	CHAR16 *name = 0, *desc = L"MikroTikBootKit";
	EFI_GUID guid;
	UINTN full_len, name_size, name_cap = 4096;
	UINTN desc_len = str_len16(desc) + 1;
	UINT16 index = 0xffff, max_index = 0xffff, i;
	BOOLEAN found = FALSE;
	VOID *data = 0, *order = 0, *new_order = 0;
	UINTN data_size = 0, order_size = 0, entries = 0;
	UINT32 attrs = 0, order_attrs = EFI_VARIABLE_NON_VOLATILE |
				      EFI_VARIABLE_BOOTSERVICE_ACCESS |
				      EFI_VARIABLE_RUNTIME_ACCESS;

	status = BS->HandleProtocol(vol_handle, &device_path_guid, (VOID **)&vol_dp);
	if (EFI_ERROR(status))
		return status;
	full = dp_with_file(vol_dp, file_path);
	if (!full)
		return EFI_OUT_OF_RESOURCES;
	full_len = dp_nodes_len(full) + 4;

	name = pool_alloc_zero(name_cap);
	if (!name) {
		status = EFI_OUT_OF_RESOURCES;
		goto out;
	}

	/* look for an entry that already points at this file, and the next free id */
	memset(&guid, 0, sizeof(guid));
	for (;;) {
		name_size = name_cap;
		status = RS->GetNextVariableName(&name_size, name, &guid);
		if (status == EFI_NOT_FOUND) {
			status = EFI_SUCCESS;
			break;
		}
		if (EFI_ERROR(status))
			goto out;
		if (!boot_var_index(name, &i))
			continue;
		if (max_index == 0xffff || i > max_index)
			max_index = i;
		status = read_variable(name, &global_variable_guid, &attrs, &data, &data_size);
		if (EFI_ERROR(status) || data_size < 6)
			continue;
		{
			UINT16 fplen = *(UINT16 *)((UINT8 *)data + 4);
			CHAR16 *d = (CHAR16 *)((UINT8 *)data + 6);
			UINTN dlen = 0;
			UINT8 *fplist;

			while (dlen < data_size && d[dlen])
				dlen++;
			fplist = (UINT8 *)(d + dlen + 1);
			if (fplen == full_len &&
			    (UINTN)(fplist - (UINT8 *)data) + fplen <= data_size &&
			    memcmp(fplist, full, full_len) == 0) {
				index = i;
				found = TRUE;
			}
			if (data)
				BS->FreePool(data);
			data = 0;
			if (found)
				break;
		}
	}
	if (!found) {
		index = (max_index == 0xffff) ? 0 : (UINT16)(max_index + 1);
	}

	/* EFI_LOAD_OPTION: attributes, FilePathListLength, description, path list */
	{
		UINTN opt_size = 4 + 2 + desc_len * 2 + full_len;
		UINT8 *opt = pool_alloc_zero(opt_size);

		if (!opt) {
			status = EFI_OUT_OF_RESOURCES;
			goto out;
		}
		*(UINT32 *)opt = EFI_LOAD_OPTION_ACTIVE;
		*(UINT16 *)(opt + 4) = (UINT16)full_len;
		memcpy(opt + 6, desc, desc_len * 2);
		memcpy(opt + 6 + desc_len * 2, full, full_len);
		boot_var_name(name, index);
		status = RS->SetVariable(name, &global_variable_guid,
					 EFI_VARIABLE_NON_VOLATILE |
					 EFI_VARIABLE_BOOTSERVICE_ACCESS |
					 EFI_VARIABLE_RUNTIME_ACCESS,
					 opt_size, opt);
		BS->FreePool(opt);
		if (EFI_ERROR(status))
			goto out;
	}

	/* BootOrder: drop the entry if present, then prepend it */
	status = read_variable(L"BootOrder", &global_variable_guid, &order_attrs,
			       &order, &order_size);
	if (EFI_ERROR(status) && status != EFI_NOT_FOUND)
		goto out;
	entries = order_size / sizeof(UINT16);
	new_order = pool_alloc_zero((entries + 1) * sizeof(UINT16));
	if (!new_order) {
		status = EFI_OUT_OF_RESOURCES;
		goto out;
	}
	((UINT16 *)new_order)[0] = index;
	{
		UINTN k = 1;

		for (i = 0; i < entries; i++)
			if (((UINT16 *)order)[i] != index)
				((UINT16 *)new_order)[k++] = ((UINT16 *)order)[i];
		status = RS->SetVariable(L"BootOrder", &global_variable_guid,
					 order_attrs, k * sizeof(UINT16), new_order);
		if (EFI_ERROR(status))
			goto out;
	}

	print(L"efiboot: boot entry Boot");
	print_hex4(index);
	print(L" -> \\EFI\\BOOT\\BOOTKIT.EFI\r\n");

out:
	if (full)
		BS->FreePool(full);
	if (name)
		BS->FreePool(name);
	if (order)
		BS->FreePool(order);
	if (new_order)
		BS->FreePool(new_order);
	return status;
}

static EFI_STATUS installer_run(EFI_HANDLE image, EFI_LOADED_IMAGE_PROTOCOL *li)
{
	EFI_STATUS status;
	EFI_FILE_PROTOCOL *root, *f, *dir;
	EFI_FILE_SYSTEM_INFO *fsi;
	EFI_HANDLE *handles = 0;
	UINTN count = 0, volumes = 0, i, choice = 0, mode = 0;
	CHAR16 *self_path;
	UINT8 info[560];
	UINTN info_size;
	UINT64 size64;
	UINTN src_len;
	VOID *src = 0;
	EFI_DEVICE_PATH_TO_TEXT_PROTOCOL *d2t = 0;
	TARGET_ID target_id;
	EFI_DEVICE_PATH_PROTOCOL *target_dp = 0;

	print(L"efiboot: installer mode\r\n");

	if (!ST->ConIn)
		return fail(EFI_UNSUPPORTED, L"no console input available");

	status = self_file_path(li, &self_path);
	if (EFI_ERROR(status))
		return fail(status, L"cannot determine my own path");

	/* read ourselves so we can write the same image elsewhere */
	status = open_root(image, &root);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open my own volume");
	status = open_file(root, self_path, &f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open my own file");
	status = file_size(f, &size64);
	if (EFI_ERROR(status))
		return fail(status, L"cannot size my own file");
	src_len = (UINTN)size64;
	status = alloc_pages(EfiLoaderData, src_len, 0xffffffffULL, &src);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate memory");
	status = read_file(f, 0, src, src_len);
	f->Close(f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot read my own file");

	/* list the volumes that look like EFI system partitions */
	status = BS->LocateHandleBuffer(EFI_BY_PROTOCOL, &simple_file_system_guid,
					0, &count, &handles);
	if (EFI_ERROR(status))
		return fail(status, L"cannot enumerate file systems");
	BS->LocateProtocol(&device_path_to_text_guid, 0, (VOID **)&d2t);

	print(L"efiboot: EFI partitions:\r\n");
	for (i = 0; i < count; i++) {
		EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
		EFI_DEVICE_PATH_PROTOCOL *dp = 0;

		if (EFI_ERROR(BS->HandleProtocol(handles[i], &simple_file_system_guid,
						 (VOID **)&fs)))
			continue;
		if (EFI_ERROR(fs->OpenVolume(fs, &root)))
			continue;
		if (EFI_ERROR(root->Open(root, &dir, L"\\EFI", EFI_FILE_MODE_READ, 0))) {
			root->Close(root);
			continue;
		}
		dir->Close(dir);
		dir = 0;

		fsi = 0;
		info_size = sizeof(info);
		if (!EFI_ERROR(root->GetInfo(root, &file_system_info_guid, &info_size, info)))
			fsi = (EFI_FILE_SYSTEM_INFO *)info;
		print(L"efiboot:   ");
		print_dec(volumes + 1);
		print(L") ");
		if (fsi && fsi->VolumeLabel[0])
			print_trunc(fsi->VolumeLabel, 32);
		else
			print(L"(no label)");
		print(L", ");
		if (fsi)
			print_dec(fsi->VolumeSize / (1024 * 1024));
		else
			print_ch(L'?');
		print(L" MB");
		if (handles[i] == li->DeviceHandle)
			print(L", this installer");
		print(L"\r\n");
		if (d2t && !EFI_ERROR(BS->HandleProtocol(handles[i], &device_path_guid,
							 (VOID **)&dp))) {
			CHAR16 *text = d2t->ConvertDevicePathToText(dp, FALSE, TRUE);

			if (text) {
				print(L"efiboot:      ");
				print_trunc(text, 68);
				print(L"\r\n");
				BS->FreePool(text);
			}
		}
		handles[volumes++] = handles[i];
	}
	if (!volumes)
		return fail(EFI_NOT_FOUND, L"no EFI partitions found");

	/* ask the user where RouterOS is installed */
	for (;;) {
		print(L"efiboot: select the EFI partition where RouterOS is installed [1-");
		print_dec(volumes);
		print(L"] (q to cancel): ");
		status = read_number(&choice);
		print(L"\r\n");
		if (status == EFI_ABORTED) {
			print(L"efiboot: cancelled\r\n");
			return EFI_ABORTED;
		}
		if (EFI_ERROR(status))
			return status;
		if (choice >= 1 && choice <= volumes)
			break;
		print(L"efiboot: invalid selection\r\n");
	}

	/* ask for the installation mode */
	print(L"efiboot: installation mode:\r\n");
	print(L"efiboot:   1) direct: copy the loader + config to the target and create the boot entry\r\n");
	print(L"efiboot:   2) removable: keep the loader here, write only the config (target stays untouched)\r\n");
	for (;;) {
		print(L"efiboot: select mode [1-2] (q to cancel): ");
		status = read_number(&mode);
		print(L"\r\n");
		if (status == EFI_ABORTED) {
			print(L"efiboot: cancelled\r\n");
			return EFI_ABORTED;
		}
		if (EFI_ERROR(status))
			return status;
		if (mode == 1 || mode == 2)
			break;
		print(L"efiboot: invalid selection\r\n");
	}

	/* open the target volume and take its partition identity */
	{
		EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *fs;
		EFI_DEVICE_PATH_PROTOCOL *dp = 0;

		if (EFI_ERROR(BS->HandleProtocol(handles[choice - 1], &simple_file_system_guid,
						 (VOID **)&fs)) ||
		    EFI_ERROR(fs->OpenVolume(fs, &root)))
			return fail(EFI_DEVICE_ERROR, L"cannot open the selected partition");
		if (EFI_ERROR(BS->HandleProtocol(handles[choice - 1], &device_path_guid,
						 (VOID **)&dp)) ||
		    !target_id_from_dp(dp, &target_id))
			return fail(EFI_NOT_FOUND, L"cannot identify the selected partition");
		target_dp = dp;
	}

	if (mode == 1) {
		/* direct install: loader + config on the target, boot entry for it */
		if (EFI_ERROR(root->Open(root, &dir, L"\\EFI",
					 EFI_FILE_MODE_READ | EFI_FILE_MODE_WRITE | EFI_FILE_MODE_CREATE,
					 EFI_FILE_DIRECTORY)))
			return fail(EFI_DEVICE_ERROR, L"cannot open \\EFI");
		dir->Close(dir);
		if (EFI_ERROR(root->Open(root, &dir, L"\\EFI\\BOOT",
					 EFI_FILE_MODE_READ | EFI_FILE_MODE_WRITE | EFI_FILE_MODE_CREATE,
					 EFI_FILE_DIRECTORY)))
			return fail(EFI_DEVICE_ERROR, L"cannot open \\EFI\\BOOT");
		dir->Close(dir);

		status = write_file(root, L"\\EFI\\BOOT\\BOOTKIT.EFI", src, src_len);
		if (EFI_ERROR(status))
			return fail(status, L"cannot write \\EFI\\BOOT\\BOOTKIT.EFI");
		status = open_file(root, L"\\EFI\\BOOT\\BOOTKIT.EFI", &f);
		if (EFI_ERROR(status))
			return fail(status, L"cannot reopen the installed file");
		status = file_size(f, &size64);
		f->Close(f);
		if (EFI_ERROR(status) || size64 != src_len)
			return fail(EFI_DEVICE_ERROR, L"installed file size mismatch");

		status = config_write(root, &target_id, target_dp);
		if (EFI_ERROR(status))
			return fail(status, L"cannot write " CONFIG_PATH);
		status = boot_entry_add(handles[choice - 1], L"\\EFI\\BOOT\\BOOTKIT.EFI");
		if (EFI_ERROR(status))
			return fail(status, L"cannot create the boot entry");
		print(L"efiboot: direct install done, copied ");
		print_dec(src_len);
		print(L" bytes to partition ");
		print_dec(choice);
		print(L"\r\n");
	} else {
		/* removable: only the config, next to the loader that is running */
		EFI_FILE_PROTOCOL *cur_root;

		status = open_root(image, &cur_root);
		if (EFI_ERROR(status))
			return fail(status, L"cannot open my own volume");
		status = config_write(cur_root, &target_id, target_dp);
		cur_root->Close(cur_root);
		if (EFI_ERROR(status))
			return fail(status, L"cannot write " CONFIG_PATH);
		print(L"efiboot: removable install done, " CONFIG_PATH L" points at partition ");
		print_dec(choice);
		print(L"\r\n");
	}

	BS->FreePool(handles);
	print(L"efiboot: press any key to reboot\r\n");
	wait_key();
	RS->ResetSystem(EfiResetCold, EFI_SUCCESS, 0, 0);
	return EFI_SUCCESS;
}

/* ---- boot -------------------------------------------------------------- */

static VOID print_kernel_version(const UINT8 *kbuf, UINTN klen)
{
	const struct SetupHeader *h = (const struct SetupHeader *)(kbuf + SETUP_HDR_OFFSET);
	UINT64 off = (UINT64)h->kernel_version + 0x200;
	CHAR16 buf[128];
	UINTN i = 0;

	if (h->kernel_version == 0 || off >= klen)
		return;
	while (i < sizeof(buf) / sizeof(buf[0]) - 1 && off + i < klen && kbuf[off + i]) {
		buf[i] = (CHAR16)kbuf[off + i];
		i++;
	}
	buf[i] = 0;
	if (i) {
		print(L"efiboot: kernel ");
		print(buf);
		print(L"\r\n");
	}
}

static EFI_STATUS boot_from_root(EFI_HANDLE image, EFI_FILE_PROTOCOL *root)
{
	struct SetupHeader hdr;
	struct BootParams *params;
	EFI_FILE_PROTOCOL *f;
	EFI_PHYSICAL_ADDRESS addr;
	EFI_STATUS status;
	UINTN setup_sects, setup_total, kalloc;
	UINT64 kfile_size, kneed, klen, ilen;
	UINT8 *kbuf = 0, *ibuf = 0;
	CHAR16 *cmd;
	handover_fn handover;

	/* -- kernel: read the first page, validate, then load it below 4G -- */

	status = open_file(root, KERNEL_PATH, &f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open " KERNEL_PATH);

	status = file_size(f, &klen);
	if (EFI_ERROR(status))
		return fail(status, L"cannot size the kernel");
	if (klen < sizeof(first_page))
		return fail(EFI_LOAD_ERROR, L"kernel file is too small");
	status = read_file(f, 0, first_page, sizeof(first_page));
	if (EFI_ERROR(status))
		return fail(status, L"cannot read the kernel");

	memcpy(&hdr, first_page + SETUP_HDR_OFFSET, sizeof(hdr));
	if (hdr.boot_flag != BOOT_FLAG_MAGIC || hdr.header != SETUP_HDR_MAGIC)
		return fail(EFI_LOAD_ERROR, L"not a Linux bzImage");
	if (hdr.version < SETUP_VERSION_2_11)
		return fail(EFI_UNSUPPORTED, L"kernel is too old for EFI handover");
	if (!hdr.relocatable_kernel)
		return fail(EFI_UNSUPPORTED, L"kernel is not relocatable");
	if (!(hdr.xloadflags & XLF_KERNEL_64) ||
	    !(hdr.xloadflags & XLF_EFI_HANDOVER_64))
		return fail(EFI_UNSUPPORTED, L"kernel has no 64-bit EFI handover entry");
	if (!hdr.syssize || !hdr.init_size)
		return fail(EFI_LOAD_ERROR, L"kernel image sizes are invalid");

	setup_sects = hdr.setup_sects ? hdr.setup_sects : 4;
	setup_total = (setup_sects + 1) * 512;
	kfile_size = setup_total + (UINT64)hdr.syssize * 16;
	if (kfile_size > klen)
		return fail(EFI_LOAD_ERROR, L"kernel image is truncated");

	/*
	 * The EFI stub copies hdr.init_size bytes starting at the protected-mode
	 * entry when it relocates the kernel, so reserve that much even when the
	 * file itself is smaller; the tail stays zero.
	 */
	kneed = setup_total + hdr.init_size;
	kalloc = (UINTN)(kneed > kfile_size ? kneed : kfile_size);
	status = alloc_pages(EfiLoaderCode, kalloc, 0xffffffffULL, (VOID **)&kbuf);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate kernel memory");
	memset(kbuf, 0, kalloc);
	status = read_file(f, 0, kbuf, (UINTN)kfile_size);
	f->Close(f);
	if (EFI_ERROR(status))
		return fail(status, L"cannot load the kernel");

	print_kernel_version(kbuf, kalloc);

	/* -- initrd: copy the embedded cpio below initrd_addr_max (0x7fffffff) -- */

	ilen = initrd_cpio_len;
	if (ilen == 0)
		return fail(EFI_LOAD_ERROR, L"embedded initrd is empty");
	status = alloc_pages(EfiLoaderData, (UINTN)ilen, 0x7fff0000ULL, (VOID **)&ibuf);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate initrd memory");
	memcpy(ibuf, initrd_cpio, (UINTN)ilen);

	/* -- boot_params -- */

	status = alloc_pages(EfiLoaderData, sizeof(*params), 0xffffffffULL, (VOID **)&params);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate boot params");
	memset(params, 0, sizeof(*params));

	/* only the setup header bytes the kernel advertises carry meaning */
	{
		UINTN hdr_len = 0x11 + hdr.setup_size;

		if (hdr_len > sizeof(struct SetupHeader))
			hdr_len = sizeof(struct SetupHeader);
		memcpy(&params->hdr, kbuf + SETUP_HDR_OFFSET, hdr_len);
	}
	params->hdr.type_of_loader = 0xff;
	params->hdr.code32_start = (UINT32)(UINTN)(kbuf + setup_total);	/* 32-bit entry */
	params->hdr.ramdisk_image = (UINT32)(UINTN)ibuf;
	params->hdr.ramdisk_size = (UINT32)ilen;
	params->ext_ramdisk_image = (UINT32)((UINT64)(UINTN)ibuf >> 32);
	params->ext_ramdisk_size = (UINT32)(ilen >> 32);

	cmd = (CHAR16 *)0;
	status = alloc_pages(EfiLoaderData, sizeof(KERNEL_CMDLINE), 0xa0000ULL, (VOID **)&cmd);
	if (EFI_ERROR(status))
		status = alloc_pages(EfiLoaderData, sizeof(KERNEL_CMDLINE), 0xffffffffULL,
				    (VOID **)&cmd);
	if (EFI_ERROR(status))
		return fail(status, L"cannot allocate the command line");
	memcpy(cmd, KERNEL_CMDLINE, sizeof(KERNEL_CMDLINE));
	params->hdr.cmd_line_ptr = (UINT32)(UINTN)cmd;
	params->ext_cmd_line_ptr = (UINT32)((UINT64)(UINTN)cmd >> 32);

	print(L"efiboot: initrd ");
	print_dec(ilen);
	print(L" bytes, booting\r\n");

	/*
	 * EFI handover entry: 32-bit handover_offset from the start of the
	 * protected-mode code and another 0x200 for the 64-bit entry.  The
	 * kernel's EFI stub takes over from here (interrupts must be off).
	 */
	addr = (EFI_PHYSICAL_ADDRESS)(UINTN)kbuf + setup_total;
	handover = (handover_fn)(UINTN)(addr + 0x200 + hdr.handover_offset);
	__asm__ volatile ("cli");
	handover(image, ST, params);
	return EFI_LOAD_ERROR;	/* not reached */
}

EFI_STATUS EFIAPI efi_main(EFI_HANDLE image, EFI_SYSTEM_TABLE *st)
{
	EFI_LOADED_IMAGE_PROTOCOL *li = 0;
	EFI_FILE_PROTOCOL *root;
	TARGET_ID target;
	EFI_STATUS status;

	ST = st;
	BS = st->BootServices;
	RS = st->RuntimeServices;

	print(L"efiboot: MikroTik boot kit loader\r\n");

	if (EFI_ERROR(BS->HandleProtocol(image, &loaded_image_protocol_guid,
					  (VOID **)&li)))
		return fail(EFI_LOAD_ERROR, L"no loaded image protocol");

	/* explicit "start the install menu" override */
	if (load_options_have(li, L"--install"))
		return installer_run(image, li);

	/*
	 * Normal case: the config next to the loader names the partition
	 * RouterOS is installed on.  Boot \EFI\BOOT\BOOTX64.EFI from there.
	 * No config (or one that does not point at a partition we can find)
	 * means the kit was not set up yet: run the install menu.
	 */
	status = open_root(image, &root);
	if (EFI_ERROR(status))
		return fail(status, L"cannot open the boot volume");
	status = config_read(root, &target);
	if (EFI_ERROR(status)) {
		print(L"efiboot: no valid " CONFIG_PATH L" here, starting the installer\r\n");
	} else {
		EFI_FILE_PROTOCOL *target_root;

		status = find_target_root(&target, &target_root);
		if (EFI_ERROR(status))
			print(L"efiboot: the configured target partition was not found\r\n");
		else
			return boot_from_root(image, target_root);
	}
	return installer_run(image, li);
}
